### PR TITLE
Update fs2 to 3.0.0-M1

### PR DESCRIPTION
**Pull request by aeons**

### CODE REVIEW

**Review by rossabaker — APPROVED** [review]
Excellent. I'm going to fork off a support branch for 1.0 before merging this.

**Comment by rossabaker** [comment]
My mistake. I thought we were already 1.0 here. I forked off a series/0.15.

**Comment by aeons** [comment]
It does have a 1.0 though, the readme is not updated.

Should we update the readme example to what's in main or should that reflect the latest stable version?

**Comment by rossabaker** [comment]
Ooof.  I thought we had a 1.0.  I was looking at the tags.  Yes, the readme should be updated.  And I'll try to find the missing tag.

**Comment by rossabaker** [comment]
Okay, I found the v1.0.0 tag.  We haven't automated the releases in this repo yet.  I'll create a maintenance branch for that, and this change will be 2.x.

**Pull request merged**
